### PR TITLE
Biffing is now an optional component.

### PR DESCRIPTION
**Pull request by Roberciiik**

### CODE REVIEW

**Comment by ALIENQuake** [comment]
@Roberciiik Shouldn't "resource biffing" be the final component (DESIGNATED value of 1000), capable of accommodating all changes made by previous components as well as any future additions?

**Comment by Roberciiik** [comment]
DESIGNATED value is not determining the order of components. If you prefer biffing could go to the end but it generally it should not be installed anyway (on massive installation general biffing should be used)

**Comment by Roberciiik** [comment]
@ALIENQuake I moved the component to the end of installation steps, as you suggested.

**Comment by ALIENQuake** [comment]
@Roberciiik Hey, sorry for the lack of communication regarding your comment, I was on vacation and forgot about it. Next time please poke me 😃

**Pull request merged**
